# Generated by Django 4.0.3 on 2022-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_delete_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='static/images/profile_pictures/dummy-picture.jpg', upload_to='static/images/profile_pictures/'),
        ),
    ]
